FROM quay.io/keycloak/keycloak:18.0.1

ENV KEYCLOAK_ADMIN=$KEYCLOAK_ADMIN
ENV KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
ENV KC_DB=$KC_DB
ENV KC_DB_USERNAME=$KC_DB_USERNAME
ENV KC_DB_PASSWORD=$KC_DB_PASSWORD
ENV KC_DB_URL_HOST=$KC_DB_URL_HOST
ENV KC_DB_URL_PORT=$KC_DB_URL_PORT
ENV KC_DB_SCHEMA=$KC_DB_SCHEMA

CMD ["start-dev"]
EXPOSE 8080
